### ISSUE TITLE
typemoq not available in definitely typed or bower registry

### ISSUE THREAD

**Issue by philsurette** [florinn/typemoq#1]
This looks like an interesting project, I'd like to use it in jasmine/karma tests. Are there any plans to register this?

$ bower search typemoq
No results.

$ tsd query typemoq

>> zero results

**Comment by florinn** [comment]
Now you should be able to install it with bower.
No need to use tsd, just install it and you can find the TS definitions in `typemoq.d.ts`

**Comment by philsurette** [comment]
Thanks! 

I was aware of the .d.ts file, however I have a gulp tsd:install task that automatically installs all .d.ts from tsd based on the contents of bower / npm dependencies. This is the only ts library I've hit so far that isn't registered at definitely typed.
