### ISSUE TITLE
It.IsAnyObject only accepts objects/interfaces that has a constructor and prototype not object literals

### ISSUE THREAD

**Issue by moanrose** [florinn/typemoq#11]
Because It.IsAnyObject expects Ctor<T>, only types and interfaces that including a constructor and prototype are valid.

But many objects are being instantiated using object literals (JSON deserialization) which does not fit this scheme.

I would suggest to add an overload for It.IsAnyObject that simply expects T

`      interface z {`
`        new ();`
`        prototype: any;`
`      }`
`      var c  = function() {}`
`      var o : z = new c();`
`      var p : z = {}; //<-- not valid`

Kind regards

**Comment by moanrose** [comment]
I guess that it is answered partially by https://github.com/florinn/typemoq/issues/3 but would a explicit typecast of and empty object to T allow the mock to be contructed?

**Comment by florinn** [comment]
For your code example, TypeScript 1.8.29 gives me the following error at the last line:
```
Error TS2322	
Type '{}' is not assignable to type 'z'.
  Property 'prototype' is missing in type '{}'.
```
What TypeScript version are you using?

**Comment by moanrose** [comment]
Dear florinn

The code that i posted was not meant to compile, but simply to illustrate that object literals could not be used as input parameter to `It.IsAnyObject` because it was restricted by the `Ctor<T>` interface.

After giving it some additional thought i realize that there are not other way to check what type an object is - runtime - than to check the prototype. And hence the `Ctor<T>` restriction

You can close the issue. Sorry for the inconvenience.

**Comment by florinn** [comment]
It's OK, @moanrose 

Let me know if you have any other suggestions to improve typemoq.
