### ISSUE TITLE
Return callback on properties?

### ISSUE THREAD

**Issue by moanrose** [florinn/typemoq#12]
Im trying to attach a return callback on a mocked property, but gets a InvalidSetupExpression Exception. 

Is this a bug/missing feature or am i using the library wrong?

`class z {`
`   x: string;`
`}`
`let w = typemoq.Mock.ofType(z);`
 `w.setup(m => m.x).returns(() => {`
 `   return "y";`
 `});`

**Comment by florinn** [comment]
For your example, the TypeScript 1.8.29 compiler outputs the following js:
```
var z = (function () {
        function z() {
        }
        return z;
    }());
    var w = TypeMoq.Mock.ofType(z);
    w.setup(function (m) { return m.x; }).returns(function () {
        return "y";
    });
```
As you may notice `x` is omitted in the output. TypeMoq throws an exception because `.setup` can't find a matching property `x`.

To make it work you should initialize prop `x`:
```
class z {
x: string = "x";
}
let w = TypeMoq.Mock.ofType(z);
w.setup(m => m.x).returns(() => {
return "y";
});
```
