### ISSUE TITLE
Setup vs Verify

### ISSUE THREAD

**Issue by SebastianStehle** [florinn/typemoq#13]
To be honest, I dont understand why there are two methods. I have used some rhino mocks and FakeItEasy and especially the last framework is much easier to use.

I would expect something like:

    undoRedoService.when(e => e.redo()).once().returns(true);
    undoRedoService.when(e => e.redo()).times(17).throws(...);

    mocks.verifyAll();

I don't like that you have to duplicate the stuff:

    undoRedoService.setup(e => e.redo())returns(true);
 
    sut.redo();

    undoRedoService.verify(e => e.redo(), Times.once());

**Comment by florinn** [comment]
One TypeMoq goal is to be super easy to use for people familiar to the popular [Moq](https://github.com/Moq/moq4) and thus TypeMoq API is similar to Moq API (which also has the `setup` - `verify` dichotomy).

Your suggestion can simplify life in certain cases, so I guess we should find a way to make it work without changing too much of the API.

Currently TypeMoq allows to mark a `setup` expression as `verifiable`:
```
undoRedoService.setup(e => e.redo()).returns(true).verifiable();
```
`verifiable` is less strict than `verify` as it only checks that it was called at least once.

Adding a `verifiable(times: Times)` overload seems to have the outcome you are expecting.

Let me know what you think.

**Comment by SebastianStehle** [comment]
I dont understand that you dont want to change your api. If you introduce a simpler method name I am fine with it, verifiable is a very complex word, at least for me :D

**Comment by florinn** [comment]
I guess "verifiable" is a bit verbose (all credit for the name goes to Moq creators ;) but since it's already in TypeMoq, IMO it would be better to stick with it and not introduce another method.
