### ISSUE TITLE
Feature Request: More Matches

### ISSUE THREAD

**Issue by SebastianStehle** [florinn/typemoq#14]
Hi, I have several feature requests:

1. TypeMoq.It.isEquals(x: any) <-- Make deep object comparison

2. TypeMoq.It.is(v => v.xyz.isEqualsTo(abc)) <-- Custom predicate

**Comment by florinn** [comment]
Thanks for the suggestions.
First request is already covered by TypeMoq.It.isValue
I'll make sure to implement the second one.
