### ISSUE TITLE
testing observable catch

### ISSUE THREAD

**Issue by b091** [florinn/typemoq#17]
Hi probably it's not issue of typemoq but maybe you can help me, and it might be a good example for this lib.

I cannot find a way to test rxjs catch...

Test code:
```typescript

  let mockHttp:TypeMoq.Mock<Http>;
  let mockErrorHandler:TypeMoq.Mock<ErrorHandler>;
  let httpJSONService:HttpJSONService;

  beforeEach(() => {
    mockHttp = TypeMoq.Mock.ofType(Http);
    mockErrorHandler = TypeMoq.Mock.ofType(ErrorHandler);
    httpJSONService = new HttpJSONService(mockHttp.object, mockErrorHandler.object);
  });

  it('logs error to console on failure', () => {
    const error:any = 'sample-error';
    mockHttp
      .setup(x => x.delete(TypeMoq.It.isAny()))
      .returns(x => Observable.throw(new Error(error))); // does not throw an error, does not trigger catch
      // .throws(new Error(error));  // <-- throws error, does not trigger catch

    httpJSONService.delete(TypeMoq.It.isAny());

    mockErrorHandler.verify(x => x.logToConsole(error), TypeMoq.Times.once());
  });
```
Code:
```typescript

 constructor(private http:Http,
             private errorHandler:ErrorHandler) {
  }

  public delete<T>(url:string):Observable<T> {
    return this.http.delete(url)
      .catch((err) => this.errorHandler.logToConsole<T>(err));
  }
```

**Comment by florinn** [comment]
Indeed it doesn't seem to be a typemoq issue.

I guess you missed subscribing to the observable stream. To trigger the catch you'd need to write:
```typescript
httpJSONService.delete(TypeMoq.It.isAny()).subscribe();
```

**Comment by b091** [comment]
Hi,

thank you for advice but unfortunately it's not a subscribe issue anyway I tried your suggestion and with it i got this result:  `TypeError: Cannot read property 'subscribe' of undefined`

I tried a lot of  different combinations and no success. All other scenarios - without throwing and handling logic inside `catch` method works like a charm. For example this:

```typescript


    it('extracts data object from response', () => {
      const response:any = 'sample-response';
      mockDataExtractor
        .setup(x => x.getString(TypeMoq.It.isAny()))
        .returns(() => TypeMoq.It.isAny());
      mockObservableAny
        .setup(x => x.map(TypeMoq.It.isAny()))
        .returns(x => Observable.of(x(response)));

      httpJSONService.post(TypeMoq.It.isAny(), TypeMoq.It.isAny());

      mockDataExtractor.verify(x => x.getJSON(response), TypeMoq.Times.once());
    });

```

**Comment by florinn** [comment]
Here is a working example starting from your initial example:
```typescript
///<reference path="node_modules/angular2/typings/browser.d.ts"/>

import * as TypeMoq from "typemoq";
import * as Rx from "rxjs/Rx";
import "rxjs/add/operator/catch";
import "reflect-metadata";
import { Http, Headers, Response } from "angular2/http";

class HttpJSONService {
    constructor(private http: Http) {
    }

    private handleError(error: any) {
        let errMsg = (error.message) ? error.message :
            error.status ? `${error.status} - ${error.statusText}` : 'error';
        console.error(errMsg);
        return Rx.Observable.throw(errMsg);
    }

    public delete<T>(url: string) {
        return this.http.delete(url)
            .catch((err) => this.handleError(err));
    }
}

let mockHttp = TypeMoq.Mock.ofType(Http);
let httpJSONService = new HttpJSONService(mockHttp.object);

//logs error to console on failure
const error: any = 'sample-error';
mockHttp
    .setup(x => x.delete(TypeMoq.It.isAny()))
    .returns(x => Rx.Observable.throw(new Error(error)));

httpJSONService.delete(TypeMoq.It.isAny()).subscribe();
```

**Comment by b091** [comment]
Thank you.... but...

It does not work for me maybe because I'm using angular2-rc.4... 
and also i want to verify it by calling `mockErrorHandler.verify(x => x.logToConsole(error), TypeMoq.Times.once());` Anyway even yours example without `verify` does not work. I'm getting error `sample-error thrown` the only thing I've changed in your code is replacing : `import { Http, Headers, Response } from "angular2/http";` with this: `import {Http, Headers, Response} from '@angular/http';`

:(

**Comment by florinn** [comment]
My previous example works for angular2-beta.17

To make it work for angular2-rc4 you need to:
* replace `import { Http, Headers, Response } from "angular2/http";` with `import { Http, Headers, Response } from "@angular/http";`
* run `typings install dt~es6-shim --global --save`
* replace `///<reference path="node_modules/angular2/typings/browser.d.ts"/>` with `/// <reference path="typings/globals/es6-shim/index.d.ts" />`

About `mockErrorHandler:TypeMoq.Mock<ErrorHandler>`, where is `ErrorHandler` coming from?

**Comment by b091** [comment]
sorry for late response, I'm also using typescript 2.

here is my simple example of this test case: [repo](https://github.com/b091/ng2-sample)

**Comment by florinn** [comment]
I was able to run the tests in your [repo](https://github.com/b091/ng2-sample) after doing the following changes in [HttpJSONService.spec.ts](https://github.com/b091/ng2-sample/blob/master/test/spec/app/http/HttpJSONService.spec.ts):
```typescript
import {Http, Response, ResponseOptions} from '@angular/http';
```
```typescript
mockDataExtractor.callBase = true;
mockErrorHandler.callBase = true;
let mockResponse: TypeMoq.Mock<Response> = TypeMoq.Mock.ofType2(Response, [ResponseOptions]);
```
```typescript
it('calls the API to remove data', () => {
...
  mockHttp
    .setup(x => x.delete(TypeMoq.It.isAny()))
    .returns(() => Observable.of(mockResponse.object));

    // when
    httpJSONService.delete(apiUrl).subscribe();
...
});

it('logs error to console on failure', () => {
...
  // when
  httpJSONService.delete(TypeMoq.It.isAny()).subscribe();
...
});
```
