### ISSUE TITLE
Reset mocks?

### ISSUE THREAD

**Issue by laurence-myers** [florinn/typemoq#18]
I have a "clock" module that provides a singleton instance, to use instead of calling "new Date()" directly. To unit test other modules that make use of the clock module, I have to mock out the singleton instance, and mock its "now()" method.

This means each invocation of "clock.now()" needs a different value. To achieve, this, for each invocation, I need to create a mock of the Clock class and inject it into the system under test (using mockery). This is not ideal; I'd much rather create a placeholder mock, inject it once, and apply a different setup within each unit test.

Is there some way to reset mocks? Or, at least, to apply "setup()" calls without falling into the "record/replay" functionality?

**Comment by florinn** [comment]
Latest typemoq (v0.3.3) includes changes to allow resetting mocks. Please give it a try.

**Comment by laurence-myers** [comment]
Oh fantastic, thanks very much! I'll give this a go. Very much appreciated! :balloon: :dancers: :+1:
