### ISSUE TITLE
Creating a Mock calls original constructor

### ISSUE THREAD

**Issue by NagRock** [florinn/typemoq#19]
When I create a mock:

`mockChatService = TypeMoq.Mock.ofType(ChatService);`

Original constructor of ChatService is called, so any code in constructor for example:

`constructor (private dataService:DataService) {
  this.dataService.addListener('sampleEvent', sampleHandler);
}`

causes null pointer exception on this.dataService.

**Comment by florinn** [comment]
Please have a look at #16
