### ISSUE TITLE
Dynamic mocking with Proxies

### ISSUE THREAD

**Issue by roblourens** [florinn/typemoq#20]
I came here with the same question as in #16, and it sounds like you need an instance of the mocked object so you can grab its properties and add them to your mock proxy. I was wondering if you ever thought about solving this with [the new ES6 Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), which would let you intercept calls in 'setup'. It's basically designed for this scenario. We would be able to write

`.setup(m => m.myFunction())`

and it would call the 'get' handler on your Proxy object with 'myFunction' as an argument, for example. Does that make sense?

I would find this especially useful because I'm trying to mock an API which is defined with a .d.ts file + a Proxy object, so there is nothing to query the properties from.

**Comment by florinn** [comment]
Thanks for the suggestion. I considered using the ES6 Proxy a while ago but made no progress due to the uneven browser support at the time.

Considering again the example in #16, using an ES6 Proxy doesn't seem to make any difference, any property of the target class remains undefined in the proxy:
```typescript
class Bar {
        value: string = '';
    }

var p = new Proxy(Bar, {});

console.log(p.value);  // p.value is undefined 
```
Please let me know if this isn't what you had in mind.

**Comment by roblourens** [comment]
That's what I would expect- if you call new Bar() then you'd be calling .value on an instance, not the class. Not what I had in mind though. I'm imagining a scenario where there is no Bar in the first place. Just an empty mock that I configure with `setup` and `returns`.

**Comment by florinn** [comment]
The Typescript compiler seems to take instance properties and constructor code and output regular Javascript constructors out of them.

To be able to omit constructor logic and still have instance props defined, I guess the TS compiler had had to generate separate code for property and object initialization, similar to what Backbone.js and Ember.js allow with their `extend`, `initialize`, `create` constructs.

**Comment by roblourens** [comment]
Right, but in my case there is no class at all, no instance props or constructor, etc. Maybe I implied the wrong thing by bringing up #16. I just want a Mock with no underlying anything.

**Comment by florinn** [comment]
Could you throw in a bit more context on what you'd like to achieve with Typemoq? Some sample code would be very helpful.

**Comment by roblourens** [comment]
Sure - let's say I have this function `doSomething` that I want to test. And it needs an object with this interface `IThing`. 
```typescript
interface IThing {
  getA(a: string): string;
  getB(b: number): number;
}

function doSomething(thing: IThing): string {
  return thing.getA("asdf") + thing.getB(123);
}
```

But, maybe I haven't implemented IThing yet. (Or maybe it's implemented by an ES6 Proxy, but I'll keep it simple).

I want to be able to do this:

```typescript
const mock = Mock.ofType<IThing>();
mock
  .setup(m => m.getA(It.isValue("asdf"))
  .returns(() => "fdsa");
mock
  .setup(m => m.getB(It.isValue(123))
  .returns(() => 321);

assert(doSomething(mock.object), "fdsa321");
```

There is still no implementation of the mocked object - but I can write a mock against an interface, with all the TS type-checks. And I think this is now theoretically possible to implement if the `m` in `setup` is implemented with an ES6 Proxy. But I don't know much about the internals of typemoq, so I don't know if it would be simple to implement, or a total paradigm change with complications, etc.

**Comment by florinn** [comment]
I see what you mean, thanks for taking time to clarify this. 

Now since Proxy works only in ES6 and typemoq targets ES5, I'm note sure what would be the best way to go about this. I can think of a couple options, keep targeting ES5 and check for Proxy availability at runtime or retarget typemoq to ES6 and hence limiting its usability to ES6. What do you think?

**Comment by roblourens** [comment]
I would probably keep targeting ES5 if I were you. I guess it depends on where your users are using it.

**Comment by florinn** [comment]
I kept ES5 as target and implemented dynamic mocking using ES6 Proxy as you suggested.
The older way of creating mocks is now known as "static mocking".

**Comment by roblourens** [comment]
Wow, I'll try it out ASAP, thanks!
