### ISSUE TITLE
Exceptions are not based on Error type

### ISSUE THREAD

**Issue by dizel3d** [florinn/typemoq#22]
Karma Runner + Chrome launcher cannot give us stack trace for errors that aren't based on Error type.
![image](https://cloud.githubusercontent.com/assets/593571/19313497/5b3f2a5a-909f-11e6-8292-bffa6de97eb1.png)

Expected behaviour:
![image](https://cloud.githubusercontent.com/assets/593571/19313488/505d99f0-909f-11e6-95a0-c041146a1084.png)

**Comment by florinn** [comment]
I assume the complaint about not receiving an Error type comes from Mocha.

Typemoq throws a MockException, so to avoid that message you could do:
```typescript
try {
// mock call
} catch (e) {
    throw new Error(e);
}
```

**Comment by dizel3d** [comment]
@florinn, you should **extend** Error, instead of **implement**.
```ts
class MyException extends Error { }

it('MyException', () => {
    const ex = new MyException();
    expect(ex instanceof Error).equal(true);
});

it('MockException', () => {
    const ex = new MockException();
    expect(ex instanceof Error).equal(true); // FAIL
});
```

**Comment by florinn** [comment]
Will do that, thanks for pointing it out.
