### ISSUE TITLE
Invalid match object

### ISSUE THREAD

**Issue by dizel3d** [florinn/typemoq#28]
``` ts
it.only('test', () => {
    const mock = Mock.ofInstance<(x) => void>(() => {});
    const anObject = {};
    mock.setup(f => f(anObject)); // throws Invalid match object
});
```

Expected the setup above is a short form of

``` ts
mock.setup(f => f(It.is(x => x === anObject)));
```

**Comment by florinn** [comment]
For object equality the setup should look like this:
```typescript
mock.setup(f => f(It.isValue(anObject)));
```

I guess having the short form is more useful than typemoq throwing "invalid match object" if an argument is not a matcher, so I'm going to change it such that `mock.setup(f => f(anObject))` will be equivalent to `mock.setup(f => f(It.isValue(anObject)))`.

**Comment by dizel3d** [comment]
Thank you! But I suggested doing **reference** equality (`It.is(x => x === anObject)`) by default. Well, you chose **deep** equality (`It.isValue(anObject)`) for that. So, could you add a function for reference equality that would be a short form for `It.is(x => x === anObject)`?

**Comment by florinn** [comment]
I guess you're right, I've changed it to do reference equality by default. Thanks.
