### ISSUE TITLE
Include name of the function call in NoSetup exceptions

### ISSUE THREAD

**Issue by ajeffrey** [florinn/typemoq#31]
hi there, first off thank you very much for building and maintaining this library. It makes testing in TypeScript so much easier and I've found it incredibly useful.

I have just one issue that makes debugging kind of difficult at times - I use MockBehavior.Strict to stop any original methods being called, but when they are called the NoSetup exception doesn't tell me what call it is. Knowing which function was called would make patching the test much easier, as it stands I have to read through my existing classes (my most-mocked test has about 7 mocked classes) and try to find out which one has a missing setup.

If you could point me in the right direction I can code something like this myself. I could add a message to the areas that call MockException with the reason as NoSetup, but I'm not sure where to pull the class or method name from.

Thanks in advance.

**Comment by florinn** [comment]
Thanks for using typemoq, glad to hear you find it useful. 
Your suggestion makes perfect sense, I'll make sure to add the needed info to the NoSetup exception asap.

**Comment by ajeffrey** [comment]
awesome, thanks!
