### ISSUE TITLE
ELIFECYCLE with 1.0.0

### ISSUE THREAD

**Issue by SebastianStehle** [florinn/typemoq#33]
I have a running karma test with webpack, jasmine and angular2. When I upgrade from 0.3.2 to 1.0.1 my test fails with 

     code ELIFECYLCE
     Exit status 32212236505

The npm-debug.log is also not helpful.

	14 verbose stack Error: squidex@1.0.0 test: `karma start --log-level debug`
	14 verbose stack Exit status 3221226505
	14 verbose stack     at EventEmitter.<anonymous> (C:\Users\mail2\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
	14 verbose stack     at emitTwo (events.js:106:13)
	14 verbose stack     at EventEmitter.emit (events.js:191:7)
	14 verbose stack     at ChildProcess.<anonymous> (C:\Users\mail2\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
	14 verbose stack     at emitTwo (events.js:106:13)
	14 verbose stack     at ChildProcess.emit (events.js:191:7)
	14 verbose stack     at maybeClose (internal/child_process.js:885:16)
	14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by florinn** [comment]
Maybe it has smth to do with typemoq 1.0.0 being an UMD module.
Can you provide some code that reproduces this issue?

**Comment by SebastianStehle** [comment]
I have no idea yet, what exactly causes the issue, sorry.

**Comment by florinn** [comment]
What errors do you get when trying to run the tests manually in the browser?

**Comment by SebastianStehle** [comment]
To be honest I am not sure how to do it in the karma/webpack context. The browser never shows up.

**Comment by florinn** [comment]
You could create an html page that references jasmine and the files from the "files" field in your karma.conf.js and see what errors you get when loading the page in a browser.

**Comment by SebastianStehle** [comment]
Sure, this will take a while I guess :(

**Comment by florinn** [comment]
Have you got the chance to test the way I suggested? What errors do you get in that case?

**Comment by SebastianStehle** [comment]
No, sorry...I am too busy at the moment and the old version works pretty fine for me

**Comment by florinn** [comment]
Closing this. When you have more context about it let me know.

**Comment by SebastianStehle** [comment]
I just realized that I upgrade it to 1.1.0 and it was just working (I used ncu, so I have not realized it :D)
