### ISSUE TITLE
Mock setup fails when using polyfilled Proxy

### ISSUE THREAD

**Issue by Wedvich** [florinn/typemoq#39]
I've got a test suite that I'm now trying to get to run under Node 4.x. As explained in the [readme](https://github.com/florinn/typemoq#dynamic-mocks), the dynamic mocks require ES6's `Proxy` object, which is not available by default in Node 4.x, and I get a `MockException ` as expected:

> MockException - invalid dynamic proxy runtime (ES6 Proxy object not detected; the dynamic mocking feature requires ES6 Proxy object support

So, to make the tests run, I've attempted to polyfill the `Proxy` object using [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill). However, now the tests fail when setting up the mocks. Here's an example of a test:

```js
const sink = TypeMoq.Mock.ofType<Sink>();
sink.setup(m => m.flush()).returns(() => Promise.resolve());
const sinkStage = new SinkStage(sink.object);
return sinkStage.flush().then(() => {
  sink.verify(m => m.flush(), TypeMoq.Times.once());
});
```

This gives me the following error instead (47:25 points to `m.flush()` inside the call to `setup`:

> TypeError: m.flush is not a function
>   at test\sink.spec.ts:47:25
>   at MethodCallReturn.MethodCall (node_modules\typemoq\dist\MethodCall.ts:28:9)
>   at new MethodCallReturn (node_modules\typemoq\dist\MethodCallReturn.ts:19:9)
>   at Function.MethodCallReturn.ofDynamicMock (node_modules\typemoq\dist\MethodCallReturn.ts:34:22)
>   at DynamicMock.setup (node_modules\typemoq\dist\DynamicMock.ts:32:37)
>   at Context.<anonymous> (test\sink.spec.ts:47:12)

Is this a problem/limitation with the Proxy polyfill, or is it TypeMoq that does something weird with it?

**Comment by florinn** [comment]
Node 4.x lacks support for ES6 Proxy, so you can't use dynamic mocking. 

`proxy-polyfill` creates static proxies, as their doc states: "... the properties you want to proxy must be known at creation time", so I assume `Sink` is a concrete type.

If that's true then you can use static mocking:
```typescript
const sink = TypeMoq.Mock.ofType(Sink);
....
```

**Comment by Wedvich** [comment]
Yep, you're right! Unfortunately `Sink` is not a concrete type, but I can just create a helper class that implements it for my tests. Thanks!
