### ISSUE TITLE
Mock method "returns" implementation is called twice

### ISSUE THREAD

**Issue by maghis** [florinn/typemoq#40]
I'm mocking a method that returns a Promise:
```
myMock.setup(x => x.method()).returns(() => Promise.reject(new Error("blah")));
```
I noticed that the "returns" implementation is executed twice even if "method" is called only once on the mock.
This should not be a problem normally, the issue is that in this particular case, the test runner is failing because it detects an unhandled promise rejection.

Is this a known behavior?

**Comment by florinn** [comment]
I assume the behavior you've noticed is not related to typemoq but to the way `Promise` works.

Can you provide some code that includes the failing expectations?
