### ISSUE TITLE
Node dependency prevents using typemoq with react native

### ISSUE THREAD

**Issue by dieseldjango** [florinn/typemoq#41]
I'm working on a react native project with typescript, and was hoping to use typemoq with it. Unfortunately typemoq depends on @types/node, which conflicts with @types/react-native.

What is it from node that typemoq requires? Would it be possible to duplicate those types rather than pull in the node type definition?

**Comment by florinn** [comment]
Indeed @types/node is a test dependency, I've added it where it belongs. Thanks.
