### ISSUE TITLE
Mocking methods that already exist on proxied object is impossible

### ISSUE THREAD

**Issue by Podlas29** [florinn/typemoq#43]
Hi.

I submitted just merged pr: https://github.com/florinn/typemoq/pull/38, but problem with callable proxy was only a half of solution to my problem.

I wrote an utility that accepts function in constructor. Second argument is an optional context, that - if provided - should be bound to function:

```javascript
constructor(fn: Function, context?: any) {
   if(context) {
      this.fn = fn.bind(context);
   } else {
      this.fn = fn;
   }
}
```
I wanted to write test for it:
```javascript
fnMock.setup(fn => fn.bind(context)).returns(fn => fn);
```
But such code results in mysterious result:
```
MockException - more than one setup expression found for ('Function.length'; setup should contain only one expression
```
First of all, this error message is not very informative. What is an 'setup expression'? It turns out that someone simply tried to call `fn.length` on my proxied function. But who? Well... `fn.bind` did! 

It turns out that in typmoq es6 proxy implemenation, if property (for example `bind`) really exists on object, it will be used, instead of mocked/proxied one.

This means that essentially all tests checking calls to functions from prototype chain are impossible to mock (at least in es6 proxy mode).

I did not provide a pr because this behaviour in code seems very deliberate, as seen here (https://github.com/florinn/typemoq/blob/master/src/Proxy/ProxyES6Handler.ts#L30). What is the reason for such behaviour and can we find a way to make existing properties 'mockable' as well?

Thanks in advance and have a great day!

**Comment by florinn** [comment]
Indeed your PR was just part of the solution due to the quirky logic required to discriminate between getters and regular methods and functions.

Please confirm if this patch fixes the issue.

**Comment by Podlas29** [comment]
This solves my use case, but could you explain further why this check for existing property on underlying object is important? I am both curious and confused.

Anyways, thanks for fast responses and fixes!

**Comment by florinn** [comment]
Typemoq uses the ES6 Proxy object for the dynamic mocking feature.

Intercepting a function/method call including the call args with the ES6 Proxy takes a couple of steps.
First to intercept the **target property name**, the ES6 Proxy calls the **handler.get** method with the target property name as one of the args.
Then to intercept the **target property args**, a function must be returned from handler.get which in turn will get called by the ES6 Proxy.

The above works fine excepting for getter methods where the second part doesn't apply. [The if statement you noticed](https://github.com/florinn/typemoq/blob/master/src/Proxy/ProxyES6Handler.ts#L29) it is used to handle this special case.

I hope the explanation makes sense, let me know otherwise.

**Comment by Podlas29** [comment]
It does... Kind of. 

I just assumed you would want to write something like:

```
mocked.setup(o => o.property).returns((() => 'property value');
```

Perhaps such usage is overkill (you can pass real object with such property after all), but for uses where object has both some methods and properties you want to mock it would make sense.

I would even assume that es6 proxy is returned recursively, so that you could write:
```
mocked.setup(object => object.firstMethod().secondMethod().someProperty).returns(() => value);
```
Perhaps such usage is rare and maybe there are some implementation problems that we are not aware of right now, but es6 proxy is so flexible, that it seems doable and (in my opinion) much more robust than assuming that user wants to mock only simple method call.


Anyways, just some food for thought. ;)

**Comment by florinn** [comment]
Definitely something to ponder about. A PR implementing the idea would be welcomed.
