### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by rbingham** [florinn/typemoq#45]
I think that this is a really cool system for mocking objects in typescript but I feel like the documentation is a little bit lacking in explaining how it is used. I have spent a couple of hours trying to figure out how to use your package. It is really hard to understand what your verify and setup functions work and what the parameters to them are. A good way to do that would be to add comments like at the end of #30.

**Comment by florinn** [comment]
Thanks for the feedback. I realize the current documentation could be a bit challenging to someone not familiar with Moq. Feel free to contribute and improve the documentation.
