### ISSUE TITLE
Add emit function to setup

### ISSUE THREAD

**Issue by rbingham** [florinn/typemoq#46]
I think that it would be cool if there was a way to have an event emitted when a function is called. This is useful for mocking streams or other objects that emit events and you are trying to make sure that when those events are emitted, the appropriate code works.

### Example
``` typescript
mock.setup(obj => load()).emit("loaded");
```

### Function Definition
``` typescript
interface IMock {
    emit(eventName: string, ...args: any[]): void
}
```

**Comment by florinn** [comment]
To emit events from a mock you could do:
```typescript
import * as TypeMoq from "typemoq";
import * as Events from "events";

let emitter = new Events.EventEmitter();
emitter.on('loaded', () => console.log('loaded event handler'));

let mock = TypeMoq.Mock.ofInstance<() => void>(() => { });

mock.setup(x => x()).returns(() => emitter.emit('loaded'));

mock.object();
```
I'm not sure if a separate `emit` construct would add enough value. Could you provide a more relevant example?
