### ISSUE TITLE
Dynamic Mock uses Proxy features that cannot be fulfilled in a ES5 engine

### ISSUE THREAD

**Issue by tiberiucorbu** [florinn/typemoq#47]
The Dynamic mocks should be somehow satisfied without using the constructor and the special Proxy features .

In the following example it is impossible to create a mock for the class `A`:

Given that

```
class A {
  constructor(b : B){
   b.foo();
  }
}

class B {
  foo(){
   console.log('foo')
  }
}
```

The constructor cannot be used in a call like this one  : 

`const AMock: TypeMoq.IMock<A> = TypeMoq.Mock.ofType<A>(A);`

Because A constructor calls B and when A is initialized B is null.

Or like this: 

`const AMock: TypeMoq.IMock<A> = TypeMoq.Mock.ofType<A>();`

Because `TypeMoq.Mock.ofType<A>()` relies on a ES6 Proxy feature that cannot be "pollyfilled".

**Comment by florinn** [comment]
To be able to create a static mock for A you'd have to supply the b constructor argument like this:
```typescript
const b: B = new B();
const AMock: TypeMoq.IMock<A> = TypeMoq.Mock.ofType<A>(A, MockBehavior.Loose, b);
```

Creating a dynamic mock for A
```typescript
const AMock: TypeMoq.IMock<A> = TypeMoq.Mock.ofType<A>();
```
doesn't call its constructor, so B cannot be part of the mock. 

For the given example, you need to create a static mock rather than a dynamic one.
