### ISSUE TITLE
TypeMoq.Mock.ofType mock property into function.

### ISSUE THREAD

**Issue by sarawut-p** [florinn/typemoq#49]
I use TypeMoq.Mock.ofType<ng.IFormController> to create a mock off ng.IFormController

It seems that the property $valid in ng.IFormController get being mock as function and i can't use it as a property anymore. i even try to assign it as a property and it make the code i am testing not work correctly

for example

if(form.$valid){} would always return true since $valid is function.

**Comment by florinn** [comment]
Could you provide a working example with a test that includes the failing expectation? 
If you can use a code playground like Plunker.
