### ISSUE TITLE
Invoking an odd-number of mocked calls reverses the precedence of the next mock call setup

### ISSUE THREAD

**Issue by lowkay** [florinn/typemoq#5]
This probably sounds a little confusing but it's easy to explain with an example. Basically, if I have multiple setups on the same function I expect the newest setup to "win", however if an odd-number of calls to the same mock is made then the oldest setup wins:

Suppose I have the following code executing:
``` TypeScript
doSomethingBig() {
    ...
    dependency.setSomeValue(value);

    const result = dependency.doSomething();
    ...
}
```

And I have the following setups:
``` TypeScript
beforeEach(() => {
    ...
    mockDependency.setup(d => d.setSomeValue(It.isAny())).returns(() => true);
    mockDependency.setup(d => d.doSomething()).returns(() => "hello");
    ...
});

it("doing something big when doing something throws error throws error", () => {
    mockDependency.setup(d => d.doSomething()).callback(() => throw new Error(););

   ...
});
```

Then I would expect my test to succeed because I have setup `doSomething` to throw after setting it up to return - newest setup wins.

However, because I have called another mock method with a setup `doSomeValue` the order is flipped and so when `doSomething` is called the first setup is executed i.e. `returns "hello"`.

I tracked this down to a suspect use of `Array.reverse` in ExtractProxyCall.

`Array.reverse` reverses in-place, which means the ordered calls on the context is mutated and flipped every time ExtractProxyCall is executed (which is once for every setup mock call). Hence, every odd-number of executed calls flips the order of the setups in the context.

**Comment by florinn** [comment]
Your explanation makes perfect sense.

Thanks for contributing!
