### ISSUE TITLE
It not possible to return falsy values for properties

### ISSUE THREAD

**Issue by Owlbertz** [florinn/typemoq#50]
Hi,

I want to test a scenario where I need
```js
if (obj.prop)
```
evaluates to false. Unfortunately, `obj.prop` is always truthy, because event if I set it up with a lambda returning `false` or `undefined` it will return a function (related to ES6 Proxy I suppose).
This occurs even if I want to return `0`.

It would be great if there was a way (besides using strict behavior) to explicitly return falsy values.

**Comment by florinn** [comment]
Could you provide a working example of a test that includes the failing expectation?
If you can use a code playground like Plunker.

**Comment by florinn** [comment]
Indeed a dynamic mock property cannot return `undefined` due to an ES6 Proxy limitation.

I've added the possibility to return falsy values (other than `undefined`).
Please install the dev version and give it a try.

**Comment by Owlbertz** [comment]
Just pulled the dev version and can confirm returning `0` now works as expected.
Is there any specific reason why `undefined` will not work?

**Comment by florinn** [comment]
Intercepting a property/getter call including the call args with the ES6 Proxy takes a couple of steps and so `undefined` is used in the `get` handler as a flag to discriminate between property values and property getters ([see here](https://github.com/florinn/typemoq/blob/master/src/Proxy/ProxyES6Handler.ts#L29)).
