### ISSUE TITLE
Mock a static class

### ISSUE THREAD

**Issue by codeandcats** [florinn/typemoq#52]
Is it possible to mock a static class?

E.g. This is a fairly common pattern in our code base...

```typescript
class Greeter {
    private static _instance: Greeter | null;
    static instance(): Greeter {
        if (!this._instance) {
            this._instance = new Greeter();
        }
        return this._instance;
    } 
    
    greet(): string {
        return 'Hello';
    }
}
```

Consumers `require` the Greeter module and use `Greeter.instance()` to get the singleton instance of `Greeter`.

I would like to mock the `instance` method so it returns my own mocked version of `Greeter`.

We use a combination of TypeMoq and [Mockery](https://github.com/mfncooper/mockery) in our tests, but this is the first time I've tried to mock a static member.

I don't see any example like this in the README. If this is possible, could an example be added?

**Comment by florinn** [comment]
The static member can be mocked this way:

```typescript
let greeter = Greeter.instance();
let mock = TypeMoq.Mock.ofType<typeof Greeter>();

mock.setup(x => x.instance()).returns(() => greeter);

expect(mock.object.instance()).to.eq(greeter);
```

Let me know if you have other questions.
