### ISSUE TITLE
Feature Request: Multiple setups for same property

### ISSUE THREAD

**Issue by Owlbertz** [florinn/typemoq#58]
Hi,

in many cases I want to mock an objects default behavior and have a specified behavior for a few tests.

E.g. I want a Service to always return a resolving promise so I can test the program flow. I am doing this by using `setup()` in Mocha's `beforeEach()`-hook.
When I now want to test the behavior when the Serve rejects the returned promise, I cannot simply use a second `setup()` call to override the first one.

See [this pen as an example](http://codepen.io/Owlbertz/pen/xdLaLe?editors=1111).

Being able to override setups would greatly improve the convenience of writing tests for me.

**Comment by jezzsantos** [comment]
You should be able to use a 'sequence' for this. see: https://github.com/florinn/typemoq#verify-expectation-invocation-order

However, I am having issues with getting that working for anything but simple typed parameters

**Comment by Owlbertz** [comment]
Hi @jezzsantos, thanks for your suggestion.

But `sequence()` seems to be intended to be used for multiple `verify()` calls.
What I want to achieve is using multiple `setup()` calls.

**Comment by florinn** [comment]
You may add multiple setups, see [Record and replay](https://github.com/florinn/typemoq#record-and-replay). 
For your example, a second call to `console.log(mock.object.myProp);` should return "Second Value".
```
interface MyMock {
  myProp: any;
}
let mock: TypeMoq.IMock<MyMock>;
    
mock = TypeMoq.Mock.ofType<MyMock>();
mock.setup((mock) => mock.myProp).returns(() => 'FirstValue'); // Set up for first time

mock.setup((mock) => mock.myProp).returns(() => 'SecondValue'); // Set up for second time

console.log(mock.object.myProp); // logs `FirstValue`

console.log(mock.object.myProp); // logs `SecondValue`
```

If you want to override the initial setup, you should reset the mock before the second setup.
```
let mock: TypeMoq.IMock<MyMock>;
    
mock = TypeMoq.Mock.ofType<MyMock>();
mock.setup((mock) => mock.myProp).returns(() => 'FirstValue'); // Set up for first time

mock.reset();

mock.setup((mock) => mock.myProp).returns(() => 'SecondValue'); // Set up for second time

console.log(mock.object.myProp); // logs `SecondValue`

console.log(mock.object.myProp); // logs `SecondValue`
```

**Comment by Owlbertz** [comment]
Hi,
I guess `reset()` is what I am looking for - thank you for pointing that out to me.
