### ISSUE TITLE
Multiple setups on same method call mutate previously recorded values

### ISSUE THREAD

**Issue by jezzsantos** [florinn/typemoq#60]
Oh boy! this one has been hard to track down, but I think I have found the bug in TypeMoq related to multiple multiple setups on the same method, but with different data. (that I thought I had found in #59 ).
(I can confirm that C# Moq does the right thing by treating recorded results as immutable)

Given the following definitions:
```
class AClass {
        property1: string;

        amethod() {
        }
    }

    class CUT {

        do(instance: AClass) {

        }
    }
```
This test fails in TypeMoq today:
```
    it('should not fail when changing recorded variables', () => {
        const mock = TypeMoq.Mock.ofType(CUT, TypeMoq.MockBehavior.Strict);

        mock.setup(f => f.do(TypeMoq.It.isObjectWith({
            property1: 'one',
        } as AClass)))
            .verifiable();
        mock.setup(f => f.do(TypeMoq.It.isObjectWith({
            property1: 'two',
        } as AClass)))
            .verifiable();

        let value = {property1: 'one'} as AClass;
        mock.object.do(value);

        value.property1 = 'two';
        mock.object.do(value);

        mock.verifyAll(); // SHOULD NOT FAIL!
    });
```
This is the stack-trace:
```
MockException - invocation count verification failed (expected invocation of CUT.do(It.isObjectWith({"property1":"one"})) at least once, invoked 0 times
 Configured setups:
 CUT.do(It.isObjectWith({"property1":"one"})), at least once
 CUT.do(It.isObjectWith({"property1":"two"})), at least once

 Performed invocations:
 CUT.do({"property1":"two"})
 CUT.do({"property1":"two"})

)
    at MockException.Error (native)
    at MockException.Exception [as constructor] (node_modules\typemoq\dist\Error\Error\Error\Exception.ts:3:9)
    at new MockException (node_modules\typemoq\dist\Error\Error\Error\MockException.ts:20:9)
    at InterceptorExecute.throwVerifyCallCountException (node_modules\typemoq\dist\InterceptorExecute.ts:65:17)
    at InterceptorExecute.verifyCallCount (node_modules\typemoq\dist\InterceptorExecute.ts:54:18)
    at InterceptorExecute.verify (node_modules\typemoq\dist\InterceptorExecute.ts:41:18)
    at StaticMock.MockBase.verifyAll (node_modules\typemoq\dist\MockBase.ts:61:31)
    at Context.it (src\sqsLoader\TypeMoqBug.ts:159:14)
```

The interesting part is the 'Performed invocations' list, that show us that at the time of the `verifyAll()` for each call to mock the data has already been changed from what it would have been on the first call.

Problem: The issue it seems (I have not looked at the TypeMoq code, but assume) that when recording a value of a call to a mock, the recorded values are being saved (as references) - 'mutable' references. 

If the CUT makes a call on the mock and then changes a value of a recorded reference that was made in that first call, the mocks recorded reference is also updated, and that causes the `verifyAll()` to see that the calls were made with the updated reference, not the data as it was at the time of the call. As we can see from the stack-trace.

Solution: The recorded data by the mock should be immutable (i.e. deep-cloned), so that teh CUT cannot mutate it later.

**Comment by jezzsantos** [comment]
This is the code to demonstrate that C# Moq does treats recorded results as immutable:

```
        [TestMethod]
        public void Should_not_fail_when_changing_recorded_variables()
        {
            var mock = new Mock<CUT>();
            mock.Setup(f => f.Do(It.Is<AClass>(a => a.Property1 == "one")));
            mock.Setup(f => f.Do(It.Is<AClass>(a => a.Property1 == "two")));

            var value = new AClass {Property1 = "one"};
            mock.Object.Do(value);

            value.Property1 = "two";
            mock.Object.Do(value);

            mock.VerifyAll();
        }
    }

    public class AClass
    {
        public string Property1 { get; set; }
    }

    public class CUT
    {
        public virtual void Do(AClass instance) {
        }
    }
```

**Comment by florinn** [comment]
Good catch, thanks for the effort. 
I've pushed a fix addressing this issue, please install the development version and let me know if it is fixed.

**Comment by jezzsantos** [comment]
Works like a beaut! amazing response @florinn thanks.

**Comment by ruszki** [comment]
In our current test cases, we need to modify arguments of a mock method, and use the modified arguments outside of the mock. So this fix brake those tests. I have classes something like this:

```
class A {   // External class, we don't want to mock this, except if it's absolutely necessary
    set(something: any): void;
    get(): any;
}

interface B {  // We mock this
    do(a: A); // ususally use A's set method
}

class C {
    private a: A;

    constructor(b: B) {
        this.a = new A();

        b.do(a);
    }

    get(): any { // Testing this
        return this.a.get();
    }
}
````

Test is failing because instance of A have to be updated by B to get something from A. Is there a nice solution for this? Besides the "making thin wrappers around external classes, and mock them" solution, which we want to avoid if possible.

**Comment by jezzsantos** [comment]
Yes, inject A into C. Otherwise you've made a fairly untestable class C.

**Comment by mindlink** [comment]
This fix does break legitimate use cases, specifically if a returns callback is implemented then you don't get the actual instance the method was called with - you get a clone of that instance. This seems like a pretty breaking change.

A good example of this is if you have event-based handlers and you want to mock the event producer so that you can raise the event in a controlled way and verify that the event is handled. Here is a trivial example, but imagine EventProducer has extra behaviour that you want to mock (so you're not going to use a real instance):

```ts
class EventProducer {
    public on(eventName: string, listener: Function, scope: any): void { ... }
}

class EventListener {
    private currentValue: string;

    constructor(private producer: EventProducer) {
        currentValue = "initial";
        producer.on("event", this.onEvent, this);
    }

    public getSomeValue(): string {
        return this.currentValue;
    }

    private onEvent(): void {
        this.currentValue = "event received";
    }
}

// -- snip

const mockProducer = Mock.ofType(EventProducer);
let listeners = [];
mockProducer.setup(p => p.on(It.isValue("event"), It.isAny(), It.isAny())).callback((name, f, scope) => {
    listeners.push(() => f.call(scope));
});

const listener = new EventListener(mockProducer.object);

// Invoke the listeners i.e. fire the event.
listeners.forEach(l => l());

expect(listener.getSomeValue()).toBe("event received");
```

This test should pass - I created a mock producer who will store all listeners for later invocation, then I expect the instance of the listener that was provided to that method to be invoked when I later call it. 

However, because the arguments are cloned by the mock I actually invoke a clone of the listener and so the expectation fails as the listener under test is never actually invoked.
