### ISSUE TITLE
"Cannot read property '___matches' of null"

### ISSUE THREAD

**Issue by Owlbertz** [florinn/typemoq#62]
Hi,

when checking if a method was called with `null` as an argument, the error
```javascript
Cannot read property '___matches' of null
```
is thrown.
See [this example](https://codepen.io/Owlbertz/pen/QvmKXj?editors=1111).

However, this seems to only be the case if the other arguments do not match. If you change the parameter of the function call so that it matches the `verify()`, everything is fine.

I would expect an argument mismatch with `null` being handled just like every other verification and to not throw this error.

**Comment by florinn** [comment]
Hi 
There was a missing null check in the error display logic. I've pushed a fix, please install the dev version and let me know if it is solved.
