### ISSUE TITLE
Converting circular JSON when printing invocation mismatch

### ISSUE THREAD

**Issue by guscastro** [florinn/typemoq#63]
When `verify`ing the number of calls of a method fails and an argument of any of the calls had an object with a circular reference, the `verify` call will throw due to attempting to `JSON.stringify` the circular reference.
`src/Common/Utils.argsName` needs changing to handle this.
Recommend using one of the circular json packages.
Happy to put in a PR myself if you like the suggested approach. Let me know.

**Comment by florinn** [comment]
Sure, sounds good. Please also include in you PR some test(s) that target this potential issue.

**Comment by florinn** [comment]
Good stuff, thanks for contributing.
