### ISSUE TITLE
Cannot use "in" with properties

### ISSUE THREAD

**Issue by stuartizon** [florinn/typemoq#64]
Trying to use the `in` operator with a mocked property, and it doesn't return what I would expect. Is this possible to change?

```
mock.setup(x => x.prop).returns(() => 'value');
console.log(`prop` in mock.object);
console.log(mock.object.prop);
```

prints `false`, `'value'`

**Comment by stuartizon** [comment]
Should have also specified I'm using a dynamic mock here:
```
interface M { prop: string };
let mock = Mock.ofType<M>();
```

**Comment by florinn** [comment]
I've pushed some changes addressing your request. Please install the development version and let me know how it goes.

**Comment by stuartizon** [comment]
Thanks! It works great now
