### ISSUE TITLE
Two more Times options

### ISSUE THREAD

**Issue by rickmugridge** [florinn/typemoq#68]
It would be handy to be able to say: Times.moreThan(number) or  Times.lessThan(number). Eg
```
bucket
            .setup(b => b.getName())
            .returns(() => "buck")
            .verifiable(TypeMoq.Times.moreThan(3));
```

**Comment by florinn** [comment]
I've added `Times.atLeast(n: number)` and `Times.atMost(n: number)` as the generalizations of existing `Times.atLeastOnce()` and `Times.atMostOnce()`. 

Please install the development version and let me know how it goes.
