### ISSUE TITLE
Accessing calls and call arguments

### ISSUE THREAD

**Issue by guscastro** [florinn/typemoq#69]
What are your thoughts on allowing access to actual call invocations on an `IMock`? E.g.:

```typescript
class AClass {
  register(registry: EventRegistry): void {
   registry.registerHandler(event => this.privateHandler(event))
  }
  private privateHandler(event: Event): void {
    // Some code I'd like to test
  }
}
const aClass = new AClass()
const mockRegistry = Mock.ofType<EventRegistry>()
aClass.register(mockRegistry.object)
const handler = mockRegistry.calls[0].args[0]
// Do something with handler...
```
This pattern allows testing of private methods without breaking encapsulation. At the moment, doing something like this is a bit verbose (involves using a `.callback` to store the argument into a variable).

**Comment by florinn** [comment]
Exposing the actual call invocations on `IMock` seems useful for scenarios like the one you described.

Still I have second thoughts about making this information readily available from `IMock` as it could encourage the bad practice of directly testing private methods.

IMO if you really want/need to break encapsulation then it is almost expected to jump through hoops to do that. That's just my two cents.
