### ISSUE TITLE
Support ECMAScript 6

### ISSUE THREAD

**Issue by rvdwijngaard** [florinn/typemoq#7]
I am using this library in my project but it does not seem to work with nodejs v5.8.0 (ES6). 

```` typescript
interface IFoo {
    hello(): string
}

class Foo  {
    constructor(public name: string) { }

    hello(): string {
        return "hi";
    }
}

var mock : Mock<IFoo> = Mock.ofType(Foo)
```` 

executing this code gives a runtime error **Class constructors cannot be invoked without 'new'**

is this a known issue?

**Comment by florinn** [comment]
The code below works fine on latest TypeMoq (v0.1.0) and node.js v6.2.0
```typescript
import typemoq = require("typemoq");

interface IFoo {
    hello(): string
}

class Foo {
    constructor(public name: string) { }

    hello(): string {
        return "hi";
    }
}

var mock: TypeMoq.Mock<IFoo> = typemoq.Mock.ofType(Foo)
mock.object.hello();
mock.verify(x => x.hello(), typemoq.Times.exactly(1));
```
Let me know if you run into issues.

**Comment by dskwarek** [comment]
It does't work with node 4.4.5

**Comment by florinn** [comment]
Indeed, it doesn't work for ES6. You're both right, my bad.
I'm going to look into it.

**Comment by florinn** [comment]
Great, thanks @rkostrzewski !
I'm going to merge your PR and then add some ES6 testing.
