### ISSUE TITLE
It.is not behaving?

### ISSUE THREAD

**Issue by stuartizon** [florinn/typemoq#71]
I've upgraded to version 1.7.0 and I'm getting an issue with tests that were previously succeeding:

```
 interface BeanParams {
      colour: string
 }

interface Service {
    getBeans(params: BeanParams): string;
}

const service = Mock.ofType<Service>();
const beanParams: BeanParams = { colour: 'red' };
service.setup(x => x.getBeans(It.is<BeanParams>(x => x === beanParams))).returns(() => 'success');
expect(service.object.getBeans(beanParams)).to.equal('success');
```

This test fails - it gives me "AssertionError: expected undefined to equal 'success'"
Logging the value of `x` in that example before comparison gives `{ colour: 'red'}`

Any ideas? Hoping I've made a stupid error :-)

**Comment by stuartizon** [comment]
For comparison, this passes on version 1.2.1

**Comment by florinn** [comment]
In later typemoq versions, the argument of the predicate is a deep clone of the target argument, thus for doing object equality comparison, `===` should be replaced by `_.isEqual`.

```
// Wrong way of doing strict object comparison
service.setup(x => x.getBeans(It.is<BeanParams>(x => x === beanParams))).returns(() => 'success');
expect(service.object.getBeans(beanParams)).to.not.eq('success');

// Right way of doing strict object comparison
service.setup(x => x.getBeans(It.is<BeanParams>(x => _.isEqual(x, beanParams)))).returns(() => 'success');
service.setup(x => x.getBeans(beanParams)).returns(() => 'success');  // Short form equivalent to the explicit form above
expect(service.object.getBeans(beanParams)).to.eq('success');
```

**Comment by stuartizon** [comment]
Ok gotcha. Thanks!

**Comment by stuartizon** [comment]
I assume that's from lodash - maybe worth calling out more explicitly that's where this is from in the readme.

**Comment by florinn** [comment]
Agree. Already done it in commit fbc6f72 :)
