### ISSUE TITLE
Conditionally calling target instance

### ISSUE THREAD

**Issue by jugglingcats** [florinn/typemoq#74]
I have a need to override the behaviour of my target instance conditionally based on previous behaviour. It's a bit of an odd requirement but cannot think of a more elegant way to do it.

Here is a contrived test, which currently fails because the setter is shadowing the target instance property.

```
    it('abc', () => {
        const targetInstance = {
            n: 0,
            getValue() {
                return this.n;
            },
            setValue(n) {
                this.n=n;
            },
            increment() {
                this.n++;
            }
        };
        const m = TypeMoq.Mock.ofInstance(targetInstance);
        m.callBase = true;

        let called = false;
        m.setup(x => x.increment()).callback(() => called = true);

        // here we want to default behaviour unless increment already called
        m.setup(x => x.getValue()).returns(() => called ? 10000 : targetInstance.getValue());

        expect(m.object.getValue()).toEqual(0);
        m.object.setValue(100);
        expect(m.object.getValue()).toEqual(100); // FAIL: expected 100, actual 0
        m.object.increment();
        expect(m.object.getValue()).toEqual(10000);
    });
```

I cannot simply replace targetInstance with m.object because of infinite regress...

This test mirrors my actual requirement quite closely: I want the target object to behave normally unless some other condition is met.

Any help much appreciated!

**Comment by florinn** [comment]
The target object is cloned when creating the mock, that's why your setup returns the initial value 0.  

I've made changes to expose the target object and to be able to control how its properties get overridden by setups (this enables having access to the target object inside `.returns`).

You should install the dev version and make a couple of changes:
```
const m = TypeMoq.Mock.ofInstance(targetInstance, undefined, false);
...
m.setup(x => x.getValue()).returns(() => called ? 10000 : m.target.getValue());
```

**Comment by jugglingcats** [comment]
Great thanks, I'll give it a go!
