### ISSUE TITLE
Modifying Properties on object parameters 

### ISSUE THREAD

**Issue by andythecoderman** [florinn/typemoq#75]
More of a question than an issue, but didn't know where else to ask. 

Is there a way to modify a property on an object passed into a mocked method and have the value stick for the calling function? 

ex:
```
moqUserRepo.setup(x => x.update(TypeMoq.It.isValue(EXISTING_USER_ID), TypeMoq.It.isAny())).returns( (userId: number, user: IUser) => {
    user.username = "Steve0";
    return Promise.resolve([1, [user]]);
  });
```

The calling function still has the original username value, not "Steve0"

**Comment by florinn** [comment]
Can you provide the full test not just the setup part?

**Comment by andythecoderman** [comment]
I'll have to create an isolated example to demonstrate the issue. Initial question is more along the lines of what the expected capability is and if I'm using the setup method correctly to modify the properties of the object passed in via the function parameters.

**Comment by florinn** [comment]
I don't see anything wrong with your setup. Here is a full working test built around it:
```
it.("abc", (done) => {

interface IUser {
  username: string
}
const EXISTING_USER_ID = 1;
const userRepoInstance = {
  update(userId: number, user: IUser): Promise<(number | IUser[])[]> {
    return Promise.reject("error");
  }
};
const userInstance = {
  username: "John"
};

const mock = TypeMoq.Mock.ofInstance(userRepoInstance, undefined, false);

mock.setup(x => x.update(TypeMoq.It.isValue(EXISTING_USER_ID), TypeMoq.It.isAny())).returns((userId: number, user: IUser) => {
  user.username = "Steve";
  return Promise.resolve([1, [user]]);
});

mock.object.update(EXISTING_USER_ID, userInstance)
  .then(function (data) {
    expect(data[0]).equal(1);
    expect(data[1][0].username).equal("Steve");
    done();
  });
});
```

**Comment by andythecoderman** [comment]
Ok so this may be the difference. I'm using TypeMoq.Mock.OfType on an interface instead of ofInstance to create the mock. I'll try to find the time to day to create a test project with that setup. 

`export const MockUserRepository: TypeMoq.IMock<IUserRepository> = TypeMoq.Mock.ofType<IUserRepository>();`

**Comment by florinn** [comment]
Using latest typemoq (v2.0.0), the example above should also work with dynamic mocking:
```
interface IUserRepository {
  update(userId: number, user: IUser): Promise<(number | IUser[])[]>;
}

const mock = TypeMoq.Mock.ofType<IUserRepository>();
...
```
