### ISSUE TITLE
Mock of Mock

### ISSUE THREAD

**Issue by david-reir** [florinn/typemoq#76]
Hi, I'm trying to access an attribute of a mock that it's also a mock. The second print doesn't work. This is the plunker: https://plnkr.co/edit/ZpU697dYHJn34RLWf971?p=preview

Am I doing something wrong?

The code is:
```
interface Data {
  msg:string
}

interface T1 {
  info:Data
}

let dataMock = TypeMoq.Mock.ofType<Data>()
dataMock.setup(x => x.msg).returns(() => 'some test')

let t1Mock = TypeMoq.Mock.ofType<T1>()
t1Mock.setup(x => x.info).returns(() => dataMock.object)

document.write(dataMock.object.msg)
document.write("<br>")
document.write(t1Mock.object.info.msg)
```

**Comment by florinn** [comment]
It's a bug. Please install latest typemoq (v2.0.1) and let me know if the issue is still present.

**Comment by david-reir** [comment]
It's working correctly now. Thanks.
