### ISSUE TITLE
Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by rickmugridge** [florinn/typemoq#77]
TypeMoq is generally working well for our team. But a common problem keeps recurring, and it's when the dependencies are complex, involving multiple mocks (and where the dependencies are not inessential). I've finally narrowed down two related problems. See the Comments that follow for sample tests that show the problems.

The following is now background....

The title exception appears sometimes when there is an incorrect setup() and where the actual argument is a mock, so that that exception message occurs instead of:

     MockException - no setup expression found for ('Function.....

I narrowed this problem down to the toString() method within the class PropertyInfo in Invocation.ts. When I put a try-catch around the access to this.name, I discovered what was going on. Likewise, with toString() in MethodGetterInvocation.

TypeError: Cannot convert a Symbol value to a string
    at PropertyInfo.toString (/API.CoreModule/node_modules/typemoq/dist/Proxy/Proxy/Proxy/ProxyES5.ts:181:35)
    at DynamicGetInvocation.ValueGetterInvocation.toString (/API.CoreModule/node_modules/typemoq/dist/Proxy/Proxy/Proxy/Invocation.ts:170:20)
    at ExtractProxyCall.handleIntercept (/API.CoreModule/node_modules/typemoq/dist/InterceptorSetup.ts:24:33)
    at /API.CoreModule/node_modules/typemoq/dist/MethodCall.ts:89:42
    at arraySome (/API.CoreModule/node_modules/lodash/lodash.js:747:11)
    at Function.some (/API.CoreModule/node_modules/lodash/lodash.js:9914:14)
    at InterceptorExecute.intercept (/API.CoreModule/node_modules/typemoq/dist/MethodCall.ts:89:5)
    at ProxyES6Handler.get (/API.CoreModule/node_modules/typemoq/dist/CurrentInterceptContext.ts:5:2)
    at Proxy.toString (<anonymous>)
    at objectToString (/API.CoreModule/node_modules/lodash/lodash.js:6571:35)
    at baseGetTag (/API.CoreModule/node_modules/lodash/lodash.js:3080:11)
    at baseClone (/API.CoreModule/node_modules/lodash/lodash.js:2663:19)
    at /API.CoreModule/node_modules/lodash/lodash.js:2702:34
    at arrayEach (/API.CoreModule/node_modules/lodash/lodash.js:537:11)
    at baseClone (/API.CoreModule/node_modules/lodash/lodash.js:2696:7)
    at /API.CoreModule/node_modules/lodash/lodash.js:2702:34
    at arrayEach (/API.CoreModule/node_modules/lodash/lodash.js:537:11)
    at baseClone (/API.CoreModule/node_modules/lodash/lodash.js:2696:7)
    at /API.CoreModule/node_modules/lodash/lodash.js:2702:34
    at arrayEach (/API.CoreModule/node_modules/lodash/lodash.js:537:11)
    at baseClone (/API.CoreModule/node_modules/lodash/lodash.js:2696:7)
    at Function.cloneDeep (/API.CoreModule/node_modules/lodash/lodash.js:11102:14)
    at new MethodInvocation (/API.CoreModule/node_modules/typemoq/dist/Proxy/Proxy/Proxy/Invocation.ts:89:61)
    at ProxyES6Handler.apply (/API.CoreModule/node_modules/typemoq/dist/InterceptorContext.ts:37:2)
    at rest.http.postForm.then (/API.CoreModule/src/client/rest/form/Form.ts:32:30)
    at <anonymous>

**Comment by rickmugridge** [comment]
Finally have a failing test that gives the error: "TypeError: Cannot convert a Symbol value to a string".

```
   it("Fails", () => {
        class LR {
            constructor(protected rd: Rd, protected i: number) {
            }
        }

        class Rd {
        }

        const mockRd = TypeMoq.Mock.ofType<Rd>(undefined, TypeMoq.MockBehavior.Strict);
        const f = TypeMoq.Mock.ofType<(lr: LR) => number>(undefined, TypeMoq.MockBehavior.Strict);
        f.setup(f => f(new LR(new Rd(), 1))).returns(() => 4);
        expect(f.object(new LR(mockRd.object, 1))).eql(4);
    });
```

A slight variation of it gives a useful error message: "MockException - no setup expression found for ('Function.({"rd":{},"i":2})'"

```
    it("OK", () => {
        class LR {
            constructor(protected rd: Rd, protected i: number) {
            }
        }

        class Rd {
        }

        const mockRd = TypeMoq.Mock.ofType<Rd>(undefined, TypeMoq.MockBehavior.Strict);
        const f = TypeMoq.Mock.ofType<(lr: LR) => number>(undefined, TypeMoq.MockBehavior.Strict);
        f.setup(f => f(new LR(new Rd(), 1))).returns(() => 4);
        expect(f.object(new LR(new Rd(), 2))).eql(4);
    });
```

**Comment by rickmugridge** [comment]
There's an associated problem with matching, which is what led me to all this:

Consider this test, which passes:

```
    it("Matches and succeeds", () => {
        class LR {
            constructor(protected rd: Rd, protected i: number) {
            }
        }

        class Rd {
        }

        const mockRd = TypeMoq.Mock.ofType<Rd>(undefined, TypeMoq.MockBehavior.Strict);
        const f = TypeMoq.Mock.ofType<(lr: LR) => number>(undefined, TypeMoq.MockBehavior.Strict);
        f.setup(f => f(TypeMoq.It.isAny())).returns(() => 4);
        expect(f.object(new LR(new Rd(), 1))).eql(4);
    });
```

But if we pass an embedded mock, it fails, even though we should accept any argument:

```
    it("Matches but fails", () => {
        class LR {
            constructor(protected rd: Rd, protected i: number) {
            }
        }

        class Rd {
        }

        const mockRd = TypeMoq.Mock.ofType<Rd>(undefined, TypeMoq.MockBehavior.Strict);
        const f = TypeMoq.Mock.ofType<(lr: LR) => number>(undefined, TypeMoq.MockBehavior.Strict);
        f.setup(f => f(TypeMoq.It.isAny())).returns(() => 4);
        expect(f.object(new LR(mockRd.object, 1))).eql(4);
    });
```

**Comment by rickmugridge** [comment]
A simpler, related problem is with logging where mocks are involved.

The same exception arises in this simple case:
          const mock = TypeMoq.Mock.ofType(Dependency, TypeMoq.MockBehavior.Strict);
          console.log(mock.object);

I don;t know if it's possible to avoid this.

**Comment by florinn** [comment]
I've pushed a fix that addresses the dynamic mock.object printing error, please install the dev version.

Regarding the other problem (the embedded mock not being matched), you should make a couple changes to your example:
* create the embedded mock as a static mock (only static mocks have the underlying target as a fully-fledged instance of the type being mocked)
```
const mockRd = TypeMoq.Mock.ofType<Rd>(Rd, TypeMoq.MockBehavior.Strict);   
```
* replace `mock.object` with `mock.target` as an argument for LR (`mock.object` returns a proxy object which is not strictly equal to the underlying target object returned by `mock.target`)
```
expect(f.object(new LR(mockRd.target, 1))).eql(4);
```

**Comment by rickmugridge** [comment]
But your "fix" only works if classes are involved, and static mocks can be used. When I found the problem, it actually involved interfaces. It was difficult to trim back to something simple to show the problem, and I ended up using classes to expose it. 

BTW, I avoid using static mocks, as they add (usually a little) extra effort without benefit in the way I TDD, design and mock.

**Comment by rickmugridge** [comment]
The *.target solution is also limited. I've trimmed it back too much.  Your solution works fine in the test code, where there is access to  the mock and thus *.target. But if the code-under-test itself is calling the constructor, it will only have access to the *.object that has been passed in.

I can create a test with this behaviour if you wish.

**Comment by rickmugridge** [comment]
Thanks for the fix for the mock.object printing error.

**Comment by rickmugridge** [comment]
Here's a different example which shows that static mocks do not (always) solve the problem.

I have a class that I'm microtesting:
```
export class HandleHerdMovementRequest {
    constructor(protected groupRepository: GroupRepository,
                protected groupProcessing: GroupProcessing,
                protected animalGroupService: AnimalGroupService,
                protected logger: Logger2) {
    }

    handle(envelope: KafkaMessageEnvelope, request: HerdMovementQuery): Promise<any> {}
}
```

Now I want to mock the constructor arguments in the simplest possible way. Let's look at AnimalGroupService:
```
export class AnimalGroupService {
    constructor(private kafkaProducer: NoKafkaProducer, topic: string) {
    }

    send(payload: AnimalMovementIn | AnimalMovementOut | GroupMovementCompletion,
         correlationId: string): Promise<any> {}
}
```

I want to mock it as a non-static mock, because I don't want to consider the details of the arguments to the AnimalGroupService constructor, because that's not relevant to my microtest. But the "Cannot convert a Symbol value to a string" problem forces me to "fix" it by using a static mock for AnimalGroupService.

So I use a static mock, which then means I need a mock for NoKafkaProducer, to pass as a constructor argument. So I use a non-static mock for that, but that then fails with "Cannot convert a Symbol value to a string". OK, so I make it a static mock, and now NoKafkaProducer instantiates and tries to connect: "2017-09-13T23:49:53.627Z ERROR no-kafka-client Metadata request failed...". 

So I am unable to proceed.

**Comment by florinn** [comment]
OK, I might have an idea how to implement what you want. Can you provide a complete example of the test failing with "Cannot convert a Symbol..."?

**Comment by rickmugridge** [comment]
Is the example I supplied above not sufficient?

**Comment by rickmugridge** [comment]
I mean the failing tests above, in the second and third comments above.

**Comment by rickmugridge** [comment]
That fails in the same way. To be clear, the whole test is:

```
    it("Match directly with .object", () => {
        class LR {
            constructor(protected rd: Rd, protected i: number) {
            }
        }

        class Rd {
        }

        const mockRd = TypeMoq.Mock.ofType<Rd>(undefined, TypeMoq.MockBehavior.Strict);
        const f = TypeMoq.Mock.ofType<(lr: LR) => number>(undefined, TypeMoq.MockBehavior.Strict);
        f.setup(f => f(new LR(mockRd.object, 1))).returns(() => 4);
        expect(f.object(new LR(mockRd.object, 1))).eql(4);
    });
```

But I see that:

```
    it("Can match a mock.object with itself", () => {
        class LR {
            constructor(protected rd: Rd, protected i: number) {
            }
        }

        class Rd {
        }

        const mockRd = TypeMoq.Mock.ofType<Rd>(undefined, TypeMoq.MockBehavior.Strict);
        expect(mockRd.object).eql(mockRd.object);
        expect(new LR(mockRd.object, 1)).eql(new LR(mockRd.object, 1));
    });
```
