### ISSUE TITLE
Can't match lambda parameter in setup

### ISSUE THREAD

**Issue by joshuakeel** [florinn/typemoq#80]
Hi there,

I'm trying to mock ngrx/store, specifically the select method. The select method takes a function, so I pass in a lambda like `state => state.compensation.filters`. TypeMoq doesn't seem to recognize this as a match when I use the same function in my real code to call select. Am I doing something wrong? When I use It.isAny(), everything works fine, but I actually need TypeMoq to respond differently based on different input parameters, so that doesn't work in my case.

```
const store = TypeMoq.Mock.ofType<Store<AppState>>();
const filtersStateStore = TypeMoq.Mock.ofType<Store<FiltersState>>();

filtersStateStore.setup(f => f.subscribe(TypeMoq.It.isAny())).callback(subscribe => {
  subscribe(filters);
});

this.store.setup(s => s.select(val => val.compensation.filters))
  .returns(() => filtersStateStore.object);
```

The last line is the important one. I provide the rest simply for context.

**Comment by florinn** [comment]
To be able to match the `select` method based on its input parameters, you should create the setup using a predicate. E.g.
```
this.store.setup(s => s.select(TypeMoq.It.is(val => val.compensation.filters !== null)))
  .returns(() => filtersStateStore.object);
```

**Comment by florinn** [comment]
Alternatively you may create your own custom matcher to better suit your scenario (see #79 ).
