### ISSUE TITLE
post install failing with typemoq

### ISSUE THREAD

**Issue by alexw10** [florinn/typemoq#82]
```
> typemoq@2.0.1 postinstall node_modules/typemoq
> postinstall-build dist

sh: 1: postinstall-build: not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! typemoq@2.0.1 postinstall: `postinstall-build dist`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the typemoq@2.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The above issue is occurring in our Jenkins build when doing `npm install`, does anyone know why this would be occurring?

**Comment by voroninpaul** [comment]
any update on this issue?

**Comment by stefanhaneveer** [comment]
I'm having the same issues on windows, and once you run it manually it doesn't handle windows paths correctly if you're user profile contains a space

**Comment by climboid** [comment]
Same problem here, any updates on fixes?

**Comment by florinn** [comment]
Might be related to `postinstall-build` and an incompatible version of npm.
What is your npm/nodejs/os ?

**Comment by bam-nutrien** [comment]
@florinn: @climboid and I are using nodejs 8.9.4 on an AWS CodeBuild Docker container right now to get this error.

**Comment by florinn** [comment]
I've removed the dependency on `postinstall-build`.
Please run 'npm install https://github.com/florinn/typemoq' and report back.

**Comment by waistcoat1971** [comment]
Did this ever get push to NPM?

**Comment by ManfredLange** [comment]
@florinn wrote on Apr 13, 2018:
> I've removed the dependency on `postinstall-build`.
> Please run 'npm install https://github.com/florinn/typemoq' and report back.

Tried this but now running into the next issue: "Error: Cannot find module './node_modules/typemoq/build/postinstall.js'

NPM version is 6.4.1. Nodejs version is 11.1.0. OS is Ubuntu 18.04.

**Comment by mbaer3000** [comment]
Same problem here. Would appreciate a new NPM package release. @florinn

**Comment by jakawell** [comment]
@florinn This is not working for me either. Also running on AWS. I'm seeing the same error that @ManfredLange is when I try installing directly from GitHub like you recommended.
